SimformSolutionsPvtLtd/chatview

CHANGELOG.md
README.md
example/android/app/build.gradle
example/android/app/src/main/AndroidManifest.xml
example/lib/data.dart
example/lib/main.dart
lib/src/models/message.dart
lib/src/models/models.dart
lib/src/models/replied_message_configuration.dart
lib/src/models/replied_msg_auto_scroll_config.dart
lib/src/models/reply_message.dart
lib/src/widgets/chat_bubble_widget.dart
lib/src/widgets/chat_groupedlist_widget.dart
lib/src/widgets/image_message_view.dart
lib/src/widgets/message_view.dart
lib/src/widgets/reply_message_widget.dart
lib/src/widgets/send_message_widget.dart
lib/src/widgets/text_message_view.dart

:sparkles: Added auto scroll to replied message feature

---

.github/pull_request_template.md
CHANGELOG.md
lib/src/widgets/reply_message_widget.dart
pubspec.yaml

Fix https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues/32 while replying to image it highlights the link instead of the image.

:bug: Fix issue while replying to image it highlights the link instead of the image.

---

CHANGELOG.md
README.md
lib/src/controller/chat_controller.dart

fix: Fix issue #35, Update README.md, update preview.

---

example/lib/main.dart
lib/src/extensions/extensions.dart
lib/src/models/feature_active_config.dart
lib/src/models/message_list_configuration.dart
lib/src/models/models.dart
lib/src/widgets/chat_bubble_widget.dart
lib/src/widgets/chat_groupedlist_widget.dart
lib/src/widgets/chat_list_widget.dart
lib/src/widgets/chat_view.dart
lib/src/widgets/chat_view_inherited_widget.dart
lib/src/widgets/image_message_view.dart
lib/src/widgets/message_view.dart
lib/src/widgets/reaction_widget.dart
lib/src/widgets/reply_message_widget.dart
lib/src/widgets/text_message_view.dart

(https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues/37) Give option to enable and disable features to user.

:sparkles: feat: Give option to enable and disable features to user

---

CHANGELOG.md
README.md
example/lib/data.dart
example/lib/main.dart
lib/src/models/reaction_popup_configuration.dart
lib/src/widgets/chat_bubble_widget.dart
lib/src/widgets/chat_groupedlist_widget.dart
lib/src/widgets/chat_list_widget.dart
lib/src/widgets/chat_view.dart
lib/src/widgets/chat_view_inherited_widget.dart
lib/src/widgets/reaction_popup.dart
lib/src/widgets/reply_message_widget.dart
lib/src/widgets/send_message_widget.dart
pubspec.yaml

feat: :hammer: Refactor code :memo: Update README.md and CHANGELOG.md.

---

CHANGELOG.md
README.md
pubspec.yaml

fix: :arrow_up: Add platforms :memo: Update README.md and CHANGELOG.md.

---

example/android/app/build.gradle

Fixes example app min sdk issue

fix: :bug: Bump minSdk in example app to match audio package requirement

---

CHANGELOG.md
README.md
example/lib/main.dart
lib/chatview.dart
lib/src/models/message.dart
lib/src/models/profile_circle.dart
lib/src/models/send_message_configuration.dart
lib/src/values/typedefs.dart
lib/src/widgets/chat_bubble_widget.dart
lib/src/widgets/chat_view.dart
lib/src/widgets/chatui_textfield.dart
lib/src/widgets/profile_circle.dart
lib/src/widgets/reply_message_widget.dart
lib/src/widgets/send_message_widget.dart
lib/src/widgets/text_message_view.dart
pubspec.yaml

:sparkles: (https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues/42) Add callback on tap of profile circle avatar. :hammer: Refactor code. :memo: Update README.md and CHANGELOG.md.

:sparkles: Add callback on tap of profile circle avatar. :hammer: Refactor code. :memo: Update README.md and CHANGELOG.md.

---

CHANGELOG.md
lib/src/models/link_preview_configuration.dart
lib/src/widgets/link_preview.dart

:sparkles: (https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues/49) Add url callback in link preview.

feat: :sparkles: (https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues/49) Add url callback in link preview.

---

CHANGELOG.md
lib/src/controller/chat_controller.dart
lib/src/extensions/extensions.dart
lib/src/models/reply_message.dart
lib/src/widgets/chat_groupedlist_widget.dart
lib/src/widgets/chat_view_appbar.dart
lib/src/widgets/image_message_view.dart
pubspec.yaml

:recycle: Refactor code.

---

CHANGELOG.md
example/lib/main.dart
lib/src/widgets/image_message_view.dart
pubspec.yaml

fix: :bug: Fix issue of image loading from file.

---

CHANGELOG.md
README.md
example/lib/main.dart
lib/src/models/reaction_popup_configuration.dart
lib/src/widgets/chat_list_widget.dart
lib/src/widgets/reaction_popup.dart
pubspec.yaml

:sparkles: (https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues/65) Add callback when user react on message.

feat: :sparkles: Add callback when user react on message.

---

pubspec.yaml

fix: :arrow_up: Upgrade version of audio wave forms.

---

.github/workflows/issue_activity_workflow.yaml

workflow: :wrench: Add issue activity workflow.

---

.github/workflows/issue_activity_workflow.yaml

:wrench: Update issue activity workflow.

---

README.md
example/lib/data.dart
example/lib/main.dart
lib/src/models/send_message_configuration.dart
lib/src/utils/debounce.dart
lib/src/values/enumaration.dart
lib/src/widgets/chatui_textfield.dart
pubspec.yaml

Added callback   `onMessageComposition `   which triggers when a user starts/stops typing a message. This method is important when a user wants to show typing indicator other side. 
Added attribute `compositionThresholdTime`  which is the threshold duration `onMessageComposition` triggers with `Composing.composed` status if the user has stopped typing.

feat: ✨ Added Callback when a user starts/stops composing typing a message.

---

example/lib/data.dart
example/lib/main.dart
lib/src/models/chat_bubble.dart
lib/src/models/chat_bubble_configuration.dart
lib/src/models/chat_user.dart
lib/src/models/emoji_message_configuration.dart
lib/src/models/image_message.dart
lib/src/models/link_preview_configuration.dart
lib/src/models/message_configuration.dart
lib/src/models/message_list_configuration.dart
lib/src/models/message_reaction_configuration.dart
lib/src/models/profile_circle.dart
lib/src/models/reaction_popup_configuration.dart
lib/src/models/replied_message_configuration.dart
lib/src/models/reply_popup_configuration.dart
lib/src/models/send_message_configuration.dart
lib/src/models/swipe_to_reply_configuration.dart
lib/src/models/type_indicator_configuration.dart
lib/src/models/voice_message_configuration.dart
lib/src/values/enumaration.dart
lib/src/widgets/chat_groupedlist_widget.dart
lib/src/widgets/chat_list_widget.dart
lib/src/widgets/chat_view.dart
lib/src/widgets/chatui_textfield.dart
lib/src/widgets/send_message_widget.dart
lib/src/widgets/voice_message_view.dart

fix :zap: Improve performance.

---

example/lib/main.dart
lib/src/models/chat_user.dart

fix :bug: Fix issue of unmodifiable list.

---

pubspec.yaml

:arrow_up: Resolve Pana issues.

---

CHANGELOG.md
pubspec.yaml

Updated http and image picker packages to the latest versions.

:arrow_up: Updated dependencies

---

pubspec.yaml

- Added CAP(^) for http and flutter_linkify version

:arrow_up: Updated dependencies http & flutter_linkify

---

CHANGELOG.md
example/lib/main.dart
lib/src/controller/chat_controller.dart
lib/src/widgets/chat_list_widget.dart

:bug: Fixed(https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues/95) Pagination is not working properly.

:bug: Fixed Issue 95

---

CHANGELOG.md
README.md
lib/src/models/send_message_configuration.dart
lib/src/widgets/chatui_textfield.dart
pubspec.yaml

fix: 🐛Added support to hide/Un-hide image picker & camera icon

---

CHANGELOG.md
README.md
lib/src/models/feature_active_config.dart
lib/src/widgets/chat_bubble_widget.dart

- Added Flags to `hideNameInChat` and `hideProfileImageInChat` to hide name and image in chat.
Closes #126 

fix: 🐛 hide user name in chat #126

---

CHANGELOG.md
lib/src/widgets/chatui_textfield.dart

fix: 🐛 fix unsupported operation issue while running on web #131

---

CHANGELOG.md
README.md
lib/src/models/message_reaction_configuration.dart
lib/src/values/typedefs.dart
lib/src/widgets/reactions_bottomsheet.dart

- Added onTap callback for reacted users

feat: ✨add onTap callback for reacted users in reactions sheet

---

CHANGELOG.md
README.md
lib/chatview.dart
lib/src/models/message_list_configuration.dart
lib/src/models/reply_message.dart
lib/src/models/send_message_configuration.dart
lib/src/values/enumeration.dart
lib/src/values/typedefs.dart
lib/src/widgets/chat_groupedlist_widget.dart
lib/src/widgets/reply_message_view.dart
pubspec.yaml

- Removed grouped_list package and implement the same group separator for message when date differ in chat.

refactor: ♻️ removed grouped_list and implement group separator for chat

---

CHANGELOG.md
lib/src/widgets/send_message_widget.dart

fix: 🐛 fix send message not working when texting start with newLine #182

---

example/android/app/build.gradle
example/android/build.gradle

fix: 🐛 fix android example

---

lib/src/widgets/chat_groupedlist_widget.dart

fix: :bug: change static bottom height in chat_groupedlist_widget.dart

---

lib/src/widgets/chat_groupedlist_widget.dart
lib/src/widgets/suggestions/suggestion_list.dart

refactor: :hammer: Update suggestion list collapse animation

---

CHANGELOG.md
pubspec.yaml

- Upgrade url_launcher to 6.3.0.

chore!: :boom: Dart Minimum Version 3.2.0

---

CHANGELOG.md

chore: :book: Updated CHANGELOG.md

---

CHANGELOG.md
pubspec.yaml

- Upgrade url_launcher to 6.3.0.

chore: :bookmark: Version Bump 2.0.0

---

.github/workflows/web-example-release.yaml

- Added web-example-release.yaml to build web app and deploy it to github pages.

ci: :construction_worker: Web Example Deployment

---

CHANGELOG.md
README.md

- Updated web example link.
- Fixed line break in CHANGELOG.md.
- Updated Preview GIF.

docs: :books: Update README.md

---

README.md

- Updated web example link.
- Fixed line break in CHANGELOG.md.
- Updated Preview GIF.

fix: :books: Update README.md

---

README.md

chore: :hammer: update README.md banner url

---

CHANGELOG.md
lib/src/widgets/chat_list_widget.dart
lib/src/widgets/chat_view.dart
lib/src/widgets/chat_view_inherited_widget.dart
lib/src/widgets/message_view.dart
lib/src/widgets/reaction_popup.dart

fix: :bug: fixed y position of reaction popup

---

CHANGELOG.md
lib/src/models/image_message.dart
lib/src/widgets/image_message_view.dart

feat: :sparkles: hide share icon for image view

---

example/android/app/src/main/AndroidManifest.xml

fix: :hammer: add record permission for android example

---

CHANGELOG.md
pubspec.yaml

chore: 🔖 Version Bump 2.1.0

---

pubspec.yaml

chore: 🔖 Version Bump 2.1.1

---

CHANGELOG.md
lib/src/widgets/chatui_textfield.dart

fix: :bug: fix mobile browser issue

---

pubspec.yaml

chore: 🔖 Version Bump 2.2.0

---

CHANGELOG.md
lib/src/widgets/chat_bubble_widget.dart
lib/src/widgets/swipe_to_reply.dart

fix: :bug: outgoing message alignment

---

pubspec.yaml

chore: :hammer: add support label for desktop and web in pubspec.yaml

---

CHANGELOG.md
lib/src/widgets/chat_view.dart

Fixes #261 : ConfigurationsInheritedWidget was out of scope in ReactionPopup, which prevented userReactionCallback from triggering.

fix: :bug: issue #261 userReactionCallback not working

---

pubspec.yaml

chore: 🔖 Version Bump 2.3.0

---

CHANGELOG.md
lib/src/widgets/voice_message_view.dart
pubspec.yaml

fix: :arrow_up: Upgrade version of audio wave forms 1.2.0

---

lib/src/widgets/voice_message_view.dart

🔨 add set finish mode method of audio waveform and set it to pause

---

CHANGELOG.md
lib/src/extensions/extensions.dart

🐛 fix date and time divider in between messages (today, yesterday)

---

CHANGELOG.md
lib/src/extensions/extensions.dart
lib/src/models/config_models/chat_bubble_configuration.dart
lib/src/widgets/link_preview.dart

feat: :sparkles: add ability to disable link preview

---

CHANGELOG.md
README.md
lib/src/models/config_models/reply_suggestions_config.dart
lib/src/values/enumeration.dart
lib/src/widgets/suggestions/suggestion_list.dart

✨ issue #251 add support of suggestion item type (Scrollable/Newline)

---

lib/src/extensions/extensions.dart
lib/src/models/config_models/chat_bubble_configuration.dart
lib/src/utils/constants/constants.dart
lib/src/utils/timeago/en_messages.dart
lib/src/utils/timeago/lookupmessages.dart
lib/src/utils/timeago/timeago.dart
lib/src/values/custom_time_messages.dart
lib/src/widgets/chat_view.dart
pubspec.yaml

Updated the timeago package with raw code since the package requires the latest version of the intl package (0.20.0). The timeago package was not up-to-date, with its last update being 5 months ago.

refactor: :hammer: dart format and timgeago package update

---

pubspec.yaml

chore: 🔖 Version Bump 2.4.0

---

pubspec.yaml

dart pub publish --dry-run suggest to use cap or range for package dependancies

chore: 🔖 version range update audio waveforms ^1.2.0

---

CHANGELOG.md
pubspec.yaml

chore: 🔖 Version Bump 2.4.1

---

doc/documentation.md
lib/src/extensions/extensions.dart
lib/src/models/config_models/base/state_config_base.dart
lib/src/models/config_models/chat_view_list/list_state_config.dart
lib/src/models/config_models/chat_view_list/load_more_config.dart
lib/src/models/config_models/chat_view_list/models.dart
lib/src/models/config_models/chat_view_state_widget_config.dart
lib/src/models/config_models/chat_view_states_configuration.dart
lib/src/models/models.dart
lib/src/utils/chat_view_locale.dart
lib/src/widgets/chat_view.dart
lib/src/widgets/chat_view_list/auto_animate_sliver_list.dart
lib/src/widgets/chat_view_list/chat_view_list.dart
lib/src/widgets/chatview_state_widget.dart

feat: :sparkles: Provide No Chats, Loading and Error States

---

doc/documentation.md
example/lib/chat_view_list_screen.dart
example/lib/data.dart
lib/src/extensions/extensions.dart
lib/src/models/config_models/chat_view_list/chat_menu_config.dart
lib/src/models/config_models/chat_view_list/last_message_status_config.dart
lib/src/models/config_models/chat_view_list/list_tile_config.dart
lib/src/models/config_models/chat_view_list/models.dart
lib/src/models/config_models/chat_view_list/user_active_status_config.dart
lib/src/values/typedefs.dart
lib/src/widgets/chat_view_list/chat_view_list_item_tile.dart
lib/src/widgets/chat_view_list/last_message_view.dart
lib/src/widgets/chat_view_list/message_status_icon.dart

feat: :sparkles: Provide Message Status Customization

---

CHANGELOG.md
doc/documentation.md
lib/src/models/config_models/chat_view_state_widget_config.dart
lib/src/models/config_models/message_configuration.dart
lib/src/models/config_models/scroll_to_bottom_button_config.dart
lib/src/models/config_models/send_message_configuration.dart
lib/src/models/config_models/voice_message_configuration.dart
lib/src/values/typedefs.dart
lib/src/widgets/chatui_textfield.dart
lib/src/widgets/chatview_state_widget.dart
lib/src/widgets/message_view.dart
lib/src/widgets/scroll_to_bottom_button.dart
lib/src/widgets/voice_message_view.dart

- Provided option for custom loading indicator in chatview states
- Provided more customization in scroll to bottom config
- Provided send button style customization
- Provided outgoing/incoming player wave styles
- Display reactions on custom message
- Provide replyMessage in Action Widgets callback

chore!: :wrench: Provide More Customizations in ChatView
