- CHANGELOG.md
- example/ios/Runner.xcodeproj/project.pbxproj
- example/ios/Runner/Info.plist
- lib/src/models/profile_circle.dart
- lib/src/widgets/chat_bubble_widget.dart
- lib/src/widgets/profile_circle.dart
:sparkles: (https://github.com/SimformSolutionsPvtLtd/flutter_chatview/issues/51) Add long press callback on profile circle avatar.
> feat: :sparkles: Add long press callback on profile circle avatar.

- lib/src/widgets/image_message_view.dart
This PR is aiming to solve the problem concerning images not showing up when trying to send an image.
In the `ImageMessageView()` file, how images were loaded previously was by checking whether the image `isMemory`. If yes then you used `Image.memory()`. But while I was testing it on my iphone, the local images selected did not start with `data:image` so the `imageUrl` was redirected to use `NetworkImage()` to load them and that was the bug.
What I changed was to use `Image.file(File(imageUrl))` to load the images and I checked whether the `!imageUrl.isUrl` or not using your already built in extension. And it worked fine.
Closes #60
[Conventional Commit]: …
> fix: Fixed image not showing issue

- lib/src/widgets/emoji_picker_widget.dart
- pubspec.yaml
This PR addresses an issue that arose due to a breaking change in a dependency of the "chatview" package. The error message, "Could not build the precompiled application for the device. Error (Xcode): ../../.pub-cache/hosted/pub.dev/chatview-1.2.1/lib/src/widgets/emoji_picker_widget.dart:67:17: Error: No named parameter with the name 'showRecentsTab'." indicated the presence of the problem.
In the recent updates of the dependency, the 'showRecentsTab' property was deprecated, which caused the package to fail. This PR replaces the deprecated 'showRecentsTab' property with the new 'recentTabBehavior' property to resolve the issue. The motive behind this change is to keep the "chatview" package updated with the latest changes in its dependencies and to ensure seamless functionality.
This PR …
> fix: Replace deprecated 'showRecentsTab' with 'recentTabBehavior' in chatview package

- CHANGELOG.md
- README.md
- lib/src/widgets/chat_groupedlist_widget.dart
- lib/src/widgets/chat_list_widget.dart
- lib/src/widgets/chat_view.dart
> feat: ✨Added field to set top padding of chat text field

- pubspec.yaml
Since updating to flutter version 3.22.0, a lot of packages are now reliant on Intl 0.19.0. This PR updates chatview to 0.19.0
Closes #145
> fix: Outdated intl dependency version

- lib/src/utils/emoji_parser.dart
- lib/src/values/typedefs.dart
- lib/src/widgets/chat_view.dart
- lib/src/widgets/emoji_picker_widget.dart
- pubspec.yaml
> ⬆️ update dependencies

- CHANGELOG.md
- README.md
- lib/chatview.dart
- lib/src/widgets/chat_list_widget.dart
- lib/src/widgets/chat_view.dart
- lib/src/widgets/emoji_picker_widget.dart
- lib/src/widgets/emoji_row.dart
- lib/src/widgets/reaction_popup.dart
> feat: ✨Added configuration for emoji picker sheet

- CHANGELOG.md
- README.md
- lib/chatview.dart
- lib/src/models/send_message_configuration.dart
- lib/src/widgets/chatui_textfield.dart
> feat:✨Added support for configuring the audio recording quality.(#121).

- CHANGELOG.md
- README.md
- lib/src/models/send_message_configuration.dart
- lib/src/widgets/chatui_textfield.dart
- Added flag to enable/disable chat text field.
- PR separated from #140.
Closes #164
> fix: 🐛 allow to enable/disable chat text field #164

- CHANGELOG.md
- README.md
- lib/src/models/send_message_configuration.dart
- lib/src/widgets/chatui_textfield.dart
- Add support to cancel voice recording.
- Add field to set icon for cancel voice record.
**Before:**
https://github.com/SimformSolutionsPvtLtd/flutter_chatview/assets/122270609/49d7119a-a109-467c-a400-c558400d0ba3
**After**
https://github.com/SimformSolutionsPvtLtd/flutter_chatview/assets/122270609/d16ea17e-83a5-48a5-bc79-ed57c8f47ed0
Closes #137 
> fix: 🐛 Added support for cancel record icon and cancel voice recording.

- CHANGELOG.md
- lib/src/widgets/send_message_widget.dart
- while replying to a message, the username is wrong in the reply message on the text field.
Before:
https://github.com/SimformSolutionsPvtLtd/flutter_chatview/assets/122270609/d0704585-133e-4601-88d4-1b1f9c6a45f8
After:
https://github.com/SimformSolutionsPvtLtd/flutter_chatview/assets/122270609/159d1bbd-7194-47eb-a932-1587090004bc
Closes #174 
> fix: 🐛 wrong username when replying to message #174

- CHANGELOG.md
- README.md
- lib/src/values/typedefs.dart
- lib/src/widgets/chat_view.dart
- lib/src/widgets/reactions_bottomsheet.dart
- lib/src/widgets/send_message_widget.dart
- Added support to customise the view for the reply on the text field.
Closes #139 
> fix: 🐛 add support for customize view for the reply of any message #139

- CHANGELOG.md
- lib/src/models/chat_user.dart
- lib/src/models/message.dart
- lib/src/models/reaction.dart
- lib/src/models/reply_message.dart
- lib/src/values/enumeration.dart
- Added tryParse methods in `MessageType`, `MessageStatus` in `enumaration.dart`
- Fixed `fromJson()`, `toJson()` methods in `message.dart`, `reaction.dart`, `reply_message.dart`
> fix!: :bug: json parsing issue

- CHANGELOG.md
- README.md
- example/lib/main.dart
- lib/src/controller/chat_controller.dart
- lib/src/extensions/extensions.dart
- lib/src/models/models.dart
- lib/src/models/profile_circle.dart
- lib/src/models/reply_suggestions_config.dart
- lib/src/models/suggestion_item_config.dart
- lib/src/models/suggestion_item_data.dart
- lib/src/models/suggestion_list_config.dart
- lib/src/utils/constants/constants.dart
- lib/src/values/enumeration.dart
- lib/src/values/typedefs.dart
- lib/src/widgets/chat_groupedlist_widget.dart
- lib/src/widgets/chat_list_widget.dart
- lib/src/widgets/chat_view.dart
- lib/src/widgets/chat_view_appbar.dart
- lib/src/widgets/chat_view_inherited_widget.dart
- lib/src/widgets/send_message_widget.dart
- lib/src/widgets/suggestions/suggestion_item.dart
- lib/src/widgets/suggestions/suggestion_list.dart
- lib/src/widgets/suggestions/suggestions_config_inherited_widget.dart
> feat: :sparkles: added reply suggestions functionality

- README.md
Updated Migration Guide in `Readme.md`
> :pencil: Update `README.md`

- CHANGELOG.md
- README.md
- example/lib/main.dart
- lib/src/controller/chat_controller.dart
- lib/src/widgets/chat_bubble_widget.dart
- lib/src/widgets/chat_list_widget.dart
- lib/src/widgets/chat_view.dart
- lib/src/widgets/chat_view_inherited_widget.dart
- lib/src/widgets/reaction_popup.dart
- lib/src/widgets/reaction_widget.dart
- lib/src/widgets/reply_message_widget.dart
- lib/src/widgets/send_message_widget.dart
> refactor!: :hammer: Move currentUser into ChatController from ChatView widget and rename chatUsers to otherUsers

- CHANGELOG.md
- CONTRIBUTING.md
- lib/src/extensions/extensions.dart
When using `provide` I got some error messages that could all be prevented at the root by checking if the state is mounted.
#187 
> fix: 🐛 correct usage of provide after unmount

- CHANGELOG.md
- lib/src/controller/chat_controller.dart
Sometimes I got errors when the receiver of these calls was unable to handle the request. This PR checks if the receiver is "healthy enough" to handle the requested call.
#187 
> fix: 🐛 prevent actions if receiver is not capable of dealing with them

- lib/src/widgets/suggestions/suggestion_list.dart
When disposing the Widget this to provide failed, thus the listener did not get removed properly.
This change fixes the call to `removeListeners`.
#187 
> fix: 🐛 correct removal of newSuggestions listener

- CHANGELOG.md
- lib/src/controller/chat_controller.dart
`_replySuggestion` should be disposed as well.
#187 
> fix: 🐛 dispose all `ValueNotifier`s and `ScrollController`s in `ChatController`.

- lib/src/widgets/chat_groupedlist_widget.dart
- lib/src/widgets/chat_list_widget.dart
- lib/src/widgets/chat_view.dart
We don't have to rebuild everything when the typing indicator should be shown/hidden.
relates to #181
part of #187 
> feat: 🌟 listen to typing indicator changes better

- CHANGELOG.md
- README.md
- lib/src/models/message.dart
> fix!: :bug: Message copyWith id value fix

- lib/src/extensions/extensions.dart
- lib/src/inherited_widgets/configurations_inherited_widgets.dart
- lib/src/widgets/chat_bubble_widget.dart
- lib/src/widgets/chat_groupedlist_widget.dart
- lib/src/widgets/chat_list_widget.dart
- lib/src/widgets/chat_view.dart
- lib/src/widgets/emoji_row.dart
- lib/src/widgets/message_time_widget.dart
- lib/src/widgets/reaction_popup.dart
- lib/src/widgets/reaction_widget.dart
- lib/src/widgets/send_message_widget.dart
- lib/src/widgets/suggestions/suggestion_item.dart
- lib/src/widgets/suggestions/suggestion_list.dart
- lib/src/widgets/type_indicator_widget.dart
> refactor: :hammer: updated config dependencies using inherited widget

- CHANGELOG.md
- lib/src/widgets/chatui_textfield.dart
> 🐛 fix: start and stop recording icons were reverse #226

- CHANGELOG.md
- lib/src/models/swipe_to_reply_configuration.dart
- lib/src/widgets/chat_bubble_widget.dart
- lib/src/widgets/reply_icon.dart
- lib/src/widgets/swipe_to_reply.dart
https://github.com/user-attachments/assets/35501c46-a0f7-4f32-b09c-0e634f69fee0
> fix: :hammer: swipe to reply gesture interaction update

- CHANGELOG.md
- lib/src/widgets/chatui_textfield.dart
fixes #232 
Before 
After 
https://github.com/user-attachments/assets/78e21498-bd5c-4d2f-b38d-08982dc1a207
> fix: :bug: the audio record cancelIcon is overflowed pixel

- CHANGELOG.md
- lib/src/models/reaction_popup_configuration.dart
- lib/src/widgets/reaction_popup.dart
> feat: :sparkles: ability to completely override userReactionCallback

- CHANGELOG.md
- lib/src/widgets/chat_list_widget.dart
- Fix if already snackBar is there then it open new snackBar on previous one.
> 🐛 fix: handle snackBar queue while reacting on message

- CHANGELOG.md
- lib/src/extensions/extensions.dart
- lib/src/widgets/chat_list_widget.dart
> fix: :bug: empty list exception

- CHANGELOG.md
- README.md
- lib/src/models/config_models/link_preview_configuration.dart
- lib/src/widgets/link_preview.dart
- Added a new field to the LinkPreviewConfiguration that provides an error message when the link is not suitable for generating a preview.
Closes #276 
> 🐛 add error message for link preview parse error #276

- CHANGELOG.md
- lib/src/widgets/link_preview.dart
Added a condition to check if the url is image-url, so it does not give broken preview for the non-image url.
Closes #317 
> :bug: Link Preview is attempted even after adding disableLinkPreview: true

- CHANGELOG.md
- lib/src/widgets/chatui_textfield.dart
https://github.com/user-attachments/assets/35529651-a165-4312-8867-95ff32e193d9
Closes #266 
[Contributor Guide]: https://github.com/SimformSolutionsPvtLtd/chatview/blob/main/CONTRIBUTING.md
> fix: 🐛 Unfocus text field before picking/capturing an image

- .gitignore
- example/.gitignore
- example/lib/chat_view_list_screen.dart
- lib/src/controller/chat_list_view_controller.dart
- lib/src/extensions/extensions.dart
- lib/src/models/chat_view_list_item.dart
- lib/src/models/config_models/chat_view_list/chat_view_list_config.dart
- lib/src/models/config_models/chat_view_list/list_tile_config.dart
- lib/src/models/config_models/chat_view_list/list_type_indicator_config.dart
- lib/src/models/config_models/chat_view_list/models.dart
- lib/src/models/config_models/chat_view_list/unread_count_config.dart
- lib/src/models/omit.dart
- lib/src/utils/chat_view_locale.dart
- lib/src/values/typedefs.dart
- lib/src/widgets/chat_view_list/chat_view_list.dart
- lib/src/widgets/chat_view_list/chat_view_list_item_tile.dart
- lib/src/widgets/chat_view_list/last_message_view.dart
- lib/src/widgets/chat_view_list/search_text_field.dart
- lib/src/widgets/chat_view_list/unread_count_view.dart
> feat: :sparkles: Add Typing Indicator in ChatViewList

- example/lib/chat_view_list_screen.dart
- lib/src/extensions/extensions.dart
- lib/src/models/chat_view_list_item.dart
- lib/src/models/config_models/chat_view_list/chat_settings.dart
- lib/src/models/config_models/chat_view_list/last_message_time_config.dart
- lib/src/models/config_models/chat_view_list/list_tile_config.dart
- lib/src/models/config_models/chat_view_list/models.dart
- lib/src/models/config_models/chat_view_list/mute_icon_config.dart
- lib/src/models/config_models/chat_view_list/pin_icon_config.dart
- lib/src/models/config_models/chat_view_list/user_avatar_config.dart
- lib/src/utils/chat_view_locale.dart
- lib/src/values/enumeration.dart
- lib/src/values/typedefs.dart
- lib/src/widgets/chat_view_list/chat_view_list.dart
- lib/src/widgets/chat_view_list/chat_view_list_item_tile.dart
> feat: :sparkles: Add Pin/Mute Icon in ChatViewList

- lib/chatview.dart
- lib/src/controller/chat_list_view_controller.dart
- lib/src/extensions/extensions.dart
- lib/src/values/enumeration.dart
- lib/src/values/typedefs.dart
> feat: :sparkles: Show Pinned Chat First in ChatViewList

- example/lib/chat_view_list_screen.dart
- lib/src/controller/chat_list_view_controller.dart
- lib/src/models/config_models/chat_view_list/chat_menu_config.dart
- lib/src/models/config_models/chat_view_list/list_tile_config.dart
- lib/src/models/config_models/chat_view_list/models.dart
- lib/src/utils/chat_view_locale.dart
- lib/src/values/enumeration.dart
- lib/src/values/typedefs.dart
- lib/src/widgets/chat_view_list/chat_list_tile_context_menu.dart
- lib/src/widgets/chat_view_list/chat_view_list.dart
- lib/src/widgets/chat_view_list/chat_view_list_item_tile.dart
> feat: :sparkles: Add Menu Option for ChatViewList

- example/lib/chat_view_list_screen.dart
- lib/src/controller/chat_list_view_controller.dart
- lib/src/models/config_models/chat_view_list/search_config.dart
- lib/src/utils/debounce.dart
- lib/src/widgets/chat_view_list/search_text_field.dart
- lib/src/widgets/chatui_textfield.dart
> feat: :sparkles: Add Debounce Option to Search in ChatViewList

- example/lib/chat_operations.dart
- lib/src/controller/chat_list_view_controller.dart
- lib/src/models/config_models/chat_view_list/chat_view_list_config.dart
- lib/src/values/typedefs.dart
- lib/src/widgets/chat_groupedlist_widget.dart
- lib/src/widgets/chat_view_list/auto_animate_sliver_list.dart
- lib/src/widgets/chat_view_list/chat_view_list.dart
- lib/src/widgets/chat_view_list/chat_view_list_item_tile.dart
- lib/src/widgets/chat_view_list/icon_scale_animation.dart
- lib/src/widgets/chat_view_list/last_message_view.dart
> feat: :sparkles: Add Animation in ChatViewList
